### ISSUE TITLE
Can you please provide more information about users file?

### ISSUE THREAD

**Issue by esteinborn** [nrwiersma/docker-afpd#1]
I'm struggling to understand how the users file works.

What is the file name?

Password hash (what kind of hash?)

Thanks

**Comment by nrwiersma** [comment]
Hi,

The users file is used to set users up on the system, which will then be used by afpd for logins by those users.

The users file is piped into ```chpasswd``` on starting the container.  You can create a new password hash using ```mkpasswd```. 

Hope that helps. Let me know if you have other questions.

**Comment by nrwiersma** [comment]
I should probably mention that the users file is volume mounted:
```-v /some/path/to/users:/users```

Just realised that my docs don't mention the names file which is also volume mounted in:
```-v /some/path/to/names:/names```
and has the format:
```
username:full name
username:full name
```

In combination these two set the users up. Will update the docs just now.

**Comment by nrwiersma** [comment]
Did this solve your issue. Can I close this issue?

**Comment by esteinborn** [comment]
Close it. I'll reopen if I still have any issues. not at work today to test.

On Jul 27, 2017, at 11:52 AM, Nicholas Wiersma <notifications@github.com> wrote:

Did this solve your issue. Can I close this issue?
