### ISSUE TITLE
mapping in /names and /users failing to create actual user account on server

### ISSUE THREAD

**Issue by esteinborn** [nrwiersma/docker-afpd#2]
I created the `names` and `users` files and mapped them to their locations in the container: `/names` `/users` but it seems as if the entrypoint.sh script is not firing.

It seems to skip `adduser -D -H $username`

as well as creating /home/$username folder

Then it doesn't chown it because it didn't create the user or the folder.

contents of `names`
```
cooluser:Web Team
```

contents of `users`
```
cooluser:$6$Hia5gFW5yn/xMMvG$ZFveCLOk78FP7ppEMq4Yop6ci3GsjkuSuIf0DKyRGzH6HY23iiXuT3z5OFVcQNM2KjaNsGLPko9rGc3yETU.Z0
```
(hash is `mkpasswd` for "test")

If I exec into the container manually and run the command `adduser -D -H cooluser` it adds the user fine. 

Then if I `passwd cooluser` to "test" I can access the afp share just fine.

Am I missing something, or doing something wrong?

Please help
**Updated the initial problem with new data**

**Comment by nrwiersma** [comment]
Hi,

Can you show me your docker run command please.

**Comment by esteinborn** [comment]
actually, just checking on this and it doesn't create the folder either,  I was creating that in a volume mapping manually.

Run command is a follows:
```
docker run -dit \
  --name afphost \
  --volume /pathto/users:/users \
  --volume /pathto/names:/names \
  --volume /pathto/afpd.conf:/usr/local/etc/afp.conf \
  nrwiersma/docker-afpd:latest
```

**Comment by nrwiersma** [comment]
Ok,

So this is quiet odd. I just tried this locally with your example users and names files and everything worked as expected. My docker run was as follows:
```
docker run -it --rm \
    --name afphost \
    -v /Users/nrwiersma/Downloads/test/users:/users \
    -v /Users/nrwiersma/Downloads/test/names:/names \
    nrwiersma/docker-afpd:latest
```

Not that I think it should change things, but what docker version are you using?

**Comment by esteinborn** [comment]
Docker version 1.12.6

Running on project atomic.

When I am inside the container, I see that the owner and group as well as CHMOD values are different than the other files in root FS:
```
drwxr-xr-x    2 root     root             6 Jun 25 17:52 mnt
-rw-rw-r--    1 1001     1002            17 Oct 31 19:09 names
dr-xr-xr-x  352 root     root             0 Nov  1 19:03 proc
drwx------    2 root     root            26 Nov  1 19:02 root
drwxr-xr-x    3 root     root            21 Nov  1 19:01 run
drwxr-xr-x    2 root     root          4096 Jul 30 14:23 sbin
drwxr-xr-x    2 root     root             6 Jun 25 17:52 srv
dr-xr-xr-x   13 root     root             0 Apr  6  2017 sys
drwxrwxrwt    2 root     root             6 Jul 30 14:23 tmp
-rw-rw-r--    1 1001     1002           115 Nov  1 16:46 users
drwxr-xr-x    7 root     root            66 Jul 30 14:23 usr
drwxr-xr-x   12 root     root           125 Jun 25 17:52 var
```

I'm going to try to add +x to them and maybe that will work.

**Comment by nrwiersma** [comment]
That is odd, as it is not what I am seeing:
```
drwxr-xr-x    2 root     root          4096 Jun 25 17:52 mnt
-rw-r--r--    1 root     root            18 Nov  1 17:41 names
dr-xr-xr-x  139 root     root             0 Nov  1 19:23 proc
drwx------    2 root     root          4096 Nov  1 19:23 root
drwxr-xr-x    2 root     root          4096 Jun 25 17:52 run
drwxr-xr-x    2 root     root          4096 Jul 30 14:23 sbin
drwxr-xr-x    2 root     root          4096 Jun 25 17:52 srv
dr-xr-xr-x   13 root     root             0 Nov  1 19:23 sys
drwxrwxrwt    2 root     root          4096 Jul 30 14:23 tmp
-rw-r--r--    1 root     root           116 Nov  1 17:41 users
drwxr-xr-x   17 root     root          4096 Nov  1 19:23 usr
```

You do have a fairly old version of docker, but that shouldnt account for this problem.

**Comment by nrwiersma** [comment]
Also my files on the host look like this:
```
-rw-r--r--  1 nrwiersma  staff    18B Nov  1 18:41 names
-rw-r--r--  1 nrwiersma  staff   116B Nov  1 18:41 users
```

**Comment by esteinborn** [comment]
So when I paste this into it's own shell script, and run it, I dont echo out from the do while loop:

```
if [ -r /users ];
then
    while IFS=":" read username name
    do
        echo "while done"
        adduser -D -H $username

        if [ ! -d "/home/$username" ]; then
            mkdir /home/$username
        fi

        chown $username:$username /home/$username

        sed -i "s/$username:\(.*\):Linux User/$username:\1:$name/g" /etc/passwd
    done < /names

    chpasswd --encrypted < /users
fi
```

**Comment by esteinborn** [comment]
and this output, as it skips the whole while loop:
```
chpasswd: unknown user cooluser
```

**Comment by nrwiersma** [comment]
in the container, can you cat the ```names``` file?

**Comment by esteinborn** [comment]
```
/ # cat names
cooluser:cooluser/ #
```

**Comment by nrwiersma** [comment]
From your original post, you said the names contained:
```
cooluser:Web Team
```
Is that what it contains on the host?

**Comment by esteinborn** [comment]
sorry, I changed to to `cooluser:cooluser` to try and remove any space characters in case that was the issue...

**Comment by esteinborn** [comment]
I think I found the problem

**Comment by nrwiersma** [comment]
Oh, just checking :)

**Comment by nrwiersma** [comment]
Oh, please do tell.

**Comment by esteinborn** [comment]
`names` and `users` files did not have an empty line at the end of the files...............

omg.

Now I have the server running and ability to connect, but not any ability to edit or add any new files, as "cooluser" is not user 1001 in group 1002, which is hte owner of that network resource I'm mapping into the container.

**Comment by nrwiersma** [comment]
Hehe, it is always the simplest of things.

As a work around to the next problem, make a dummy user before cooluser. Alpine will start numbering new users as 1000, so cooluser is user 1000. If you make a dummy user first, cooluser will become 1001.

**Comment by esteinborn** [comment]
Thats perfect. Only issue left was that the root mapped folder inside /media was owned by root, so i just added a line to my script that runs a `docker exec -t afphost bash -c "chown cooluser /media/myfolder`

**Comment by nrwiersma** [comment]
Awesome, glad you got it all working.

**Comment by esteinborn** [comment]
Thanks for all the help and quick replies. Really nice little docker container here!

**Comment by nrwiersma** [comment]
Thanks. It is really no issue. Happy playing :)
