### ISSUE TITLE
Would you mind pushing a new release?

### ISSUE THREAD

**Issue by esteinborn** [nrwiersma/docker-afpd#3]
I'm using :latest tag, which is different than the 2.0.0 tag, but am looking to lock down the semver of this container image. Any way you can tag a new 2.0.1 release with all the changes from the latest commit?

Thanks!

**Comment by nrwiersma** [comment]
Sure. Done. `2.1.0` is tagged.

**Comment by esteinborn** [comment]
Perfect, worked like a charm! thanks for maintaining this!
